/*
 * ViewerWindow.java
 *
 * Created on 26 December 2008, 17:17
 */

package ui.log;

import java.awt.Point;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

import java.util.Collection;
import javax.swing.JCheckBox;
import ui.CircuitPanel;

/**
 *
 * @author  matt
 */
public class ViewerWindow extends javax.swing.JFrame {
    private CircuitPanel circuit;

    /** Creates new form ViewerWindow */
    public ViewerWindow(CircuitPanel circuit) {
        this.circuit = circuit;
        initComponents();

        viewerpanel.addComponentListener(new ComponentAdapter(){
            @Override
            public void componentResized(ComponentEvent e) {
                 jScrollPane1.getViewport().setViewPosition(new Point(viewerpanel.getWidth(),0));
            }
        });
                  
    }
    
    public ViewerWindow(PinLogger pl){
        initComponents();
        ((Viewer) viewerpanel).addLogger(pl);
        
        viewerpanel.addComponentListener(new ComponentAdapter(){
            @Override
            public void componentResized(ComponentEvent e) {
                jScrollPane1.getViewport().setViewPosition(new Point(viewerpanel.getWidth(),0));
            }
        });
        
    }
    
    public void addPinLoggers(Collection<PinLogger> cpl){
        int yOffset = 0;
        int count = 0;
        for(final PinLogger pl: cpl){  
            ((Viewer) viewerpanel).addLogger(pl); 
            
            JCheckBox newCheckBox = new JCheckBox();
            newCheckBox.setText(count + ". " + pl.getName()); 
            newCheckBox.setSelected(pl.isEnabled());
            newCheckBox.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pl.setEnabled(!pl.isEnabled());
                }
            });
            CheckboxPanel.add(newCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, yOffset, -1, -1));
            
            yOffset += 20;
            count++;
        }

        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewerpanel = new Viewer();
        jScrollPane2 = new javax.swing.JScrollPane();
        CheckboxPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ui/Bundle"); // NOI18N
        setTitle(bundle.getString("ViewerWindow.title")); // NOI18N

        jToolBar1.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/buttons/toolbar/gtk-edit.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/buttons/toolbar/document-properties.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/buttons/toolbar/appointment-new.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout viewerpanelLayout = new javax.swing.GroupLayout(viewerpanel);
        viewerpanel.setLayout(viewerpanelLayout);
        viewerpanelLayout.setHorizontalGroup(
            viewerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        viewerpanelLayout.setVerticalGroup(
            viewerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(viewerpanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        CheckboxPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane2.setViewportView(CheckboxPanel);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.EAST);

        pack();
    }//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CheckboxPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel viewerpanel;
    // End of variables declaration//GEN-END:variables

}
